name: captcha_view
description: A new Flutter package.
version: 0.0.1
author: Oliver Chu
homepage: https://github.com/oliverchu/captcha_view

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/ic_puzzle.png
    - assets/images/ic_verify_bg.jpeg